---
# powershell version: kubectl create clusterrolebinding monitor-pods --clusterrole=monitor-pods --serviceaccount=test:monitor-pods-acc
apiVersion: rbac.authorization.k8s.io   # also try w/o "v1"
kind: ClusterRoleBinding
metadata:
  name: monitor-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-pods
  # namespace: test
subjects:
- kind: ServiceAccount
  name: monitor-pods-acc
  # namespace: test