# create clusterrole and clusterrolebinding (look at createRBAC.ps1)
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-pods-acc
  namespace: test

---
# powershell version: kubectl create clusterrole monitor-pods --verb=get,watch,list --resource=pods
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitor-pods
  namespace: test
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
# powershell version: kubectl create clusterrolebinding monitor-pods --clusterrole=monitor-pods --serviceaccount=test:monitor-pods-acc
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitor-pods
subjects:
- kind: ServiceAccount
  name: monitor-pods-acc
  namespace: test
